-- ====================================================================
-- Retail Customer Shopping Behavior Analysis
-- Author: Chilakala Surya Prakash
-- Description: Business SQL queries to analyze customer demographics,
--              purchasing drivers, product trends, and subscription behavior.
-- ====================================================================

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    COUNT(customer_id) AS total_customers
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, 
    gender,
    item_purchased,
    purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS avg_product_rating,
    COUNT(customer_id) AS total_reviews
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC, total_reviews DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, 
    COUNT(customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare spend metrics between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. What are the top 3 most popular payment methods used by high-spending customers (> $70 spend)?
SELECT 
    payment_method,
    COUNT(customer_id) AS transaction_count,
    SUM(purchase_amount) AS total_revenue
FROM customer
WHERE purchase_amount > 70
GROUP BY payment_method
ORDER BY transaction_count DESC
LIMIT 3;


-- Q7. Age Group Segmentation: Categorize customers into age brackets and analyze revenue distribution.
SELECT 
    CASE 
        WHEN age < 25 THEN 'Under 25'
        WHEN age BETWEEN 25 AND 40 THEN '25-40'
        WHEN age BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END AS age_group,
    COUNT(customer_id) AS total_customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY 
    CASE 
        WHEN age < 25 THEN 'Under 25'
        WHEN age BETWEEN 25 AND 40 THEN '25-40'
        WHEN age BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END
ORDER BY total_revenue DESC;
